### ISSUE TITLE
List all auctions

### ISSUE THREAD

**Issue by johnsson84** [TommyDahlin/Celemo#19]
- [ ] Create auction model
- [ ] Create auction repo
- [ ] Create auction service
- [ ] Create auction controller
- [ ] FindAll funtion in service to find all auctions
- [ ] Create endpoint in controller to get list of auctions
