### ISSUE TITLE
USER STORIES

### ISSUE THREAD

**Issue by NybergViktor** [TommyDahlin/Celemo#33]
- [x] As a user i want to be able to report an auctions or a users content if it is inappropriate. POST #43 
- [x] As a user I want to be able to create an account. (Authenticator via email, Later.) POST #23 
- [x] As a user i should be able to make bids. POST 
- [ ] As a user i want to be able to send comments/messages to other users. POST #34
- [x] As a user I should be able to make an auction listing. User has account. POST #35 & #20
- [x] As a user I want to be able to add an auction to a favourite list on my profile page. POST/PUT #36
- [x] As a user I want to be able to pick a default profile picture or upload a personal picture. POST/PUT #50 
- [x] As a visitor/user i want to be able to use a filtered search function so that i can choose between different categories such as: type of auction, category. KRAV. GET #17 
- [x] As a user i want to be able to see my bidding history from expired auction listings. KRAV GET #29 
- [x] As a visitor/user I should be able to see time left on a listing. GET #20 
- [x] As a user I want to be able to see my transactions. Bought items. GET #54 
- [x] As a user i want to be able to see all my active listings. GET #20 
- [x] As a user i want to be able to see all my completed listings. GET #20 
- [x] As a user I should be able to see previous bids on a listing. GET #29
- [x] As a user I should be able to see final prices of a listing. GET #20 
- [x] As a user i should be able to see my account balance. GET #38 
- [x] As a visitor I should be able too see all auctions without having an account. GET #20 
- [ ] As a user i should be able to deposit or withdraw money to/from my account balance. PUT #51 
- [x] As a user I want to be able to modify/delete my auction. PUT #20 
- [x] As an admin I can delete or modify auctions if there is something inappropriate with an auction. PUT #37 
- [ ] As a user I want to be able to delete my account. Fake delete (Are you sure?, Really sure? Really really really sure??) DELETE #49 
- [x] As a user I want to be able to delete my auction. DELETE #20 
- [x] As an admin I can see a list of a users transactions. DELETE #37 
- [x] As an admin I want a flagged category for reported listings so I can remove if an auction is inappropriate. DELETE #37 
- [x] As an admin I want to be able to delete user account. DELETE #37
