### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by NybergViktor** [TommyDahlin/Celemo#37]
These needs to work:
 
- [x] get all auctions
- [x] get all users
- [x] delete auction
- [x] put auction (modify)
- [x] get userId transactions // In #158 both USER and ADMIN have access to this method.
- [x] get flagged auctions
- [x] #47 
- [x] delete userId account
